### ISSUE TITLE
Project tags margin misalignment on subsequent lines

### ISSUE THREAD

**Issue by BretHudson** [thienjs/thien.me#1]
![image](https://user-images.githubusercontent.com/1000405/154852516-409929eb-379a-42cc-a1ee-1a49f5acc5d7.png)

![image](https://user-images.githubusercontent.com/1000405/154852529-7721bf33-1d3f-4e55-83fe-96d6c79c7fc6.png)

By using [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) on the `flex` parent instead of `margin-left`/`margin-right` on each child, you'll be able to not only keep the first item in rows 2+ from being misaligned, but you'll also be able to apply a vertical gap applied as well :)

![image](https://user-images.githubusercontent.com/1000405/154852669-ce2216d7-6531-46fa-b345-4dbea2256419.png)

**Comment by thien-io** [comment]
Thanks! I was wondering how to align the tags better. This is very helpful.

**Comment by BretHudson** [comment]
Resolved by thienjs/thien.me#1
